### PR TITLE
Add Inputs to Sliders

### PR DESCRIPTION
**Pull request by jenusi**

### CODE REVIEW

**Review by Taiga74164 — COMMENTED** [review]
Feedback:
- CTRL + Click exists
- Drag doesn't have any visual feed back
- Also, you're not setting a max value and the speed is incredibly high for some of them

**Comment by jenusi** [comment]
Oh, I misplaced the minimum & maximum value. It's also possible to adjust the speed. I'll change the pull request now, try it again in a minute.

**Comment by Taiga74164** [comment]
but stiLl, why should we use drag and not slider

**Comment by jenusi** [comment]
Most people don't know about CTRL + Left Click, there has also been an issue about this already. And you could also theoretically use my first solution in the first commit, but I thought the drag would be better.
But if you prefer the slider, it's your decision.

**Comment by Taiga74164** [comment]
We lose more using Drag. I suggest creating a wrapper for Sliders if you really wanna have extended functionality.

**Pull request closed without merging**
